language: objective-c
osx_image: xcode7.1
env:
global:
    - "MODULE_NAME=ti.crypto"
before_install:
    - MODULE_ROOT=$PWD
    - brew update
    - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
    - brew tap caskroom/versions
    - sudo rm -rf /Library/Java/JavaVirtualMachines
    - brew cask install caskroom/versions/java7
install:
    - cd $MODULE_ROOT
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh -s "--branch 5_1_X"
script: 
    - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script.sh
    - source script.sh
after_success: # and this only on success
    - curl -o deploy.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/deploy.sh
    - source deploy.sh
